// @ts-check
import nextConfig from "eslint-config-next";

/** @type {import("eslint").Linter.Config[]} */
const config = [
  ...nextConfig,
  {
    ignores: [
      ".open-next/**",
      ".wrangler/**",
      "playwright-report/**",
      "test-results/**",
      "coverage/**",
      "workers/cron/dist/**",
      // Generated by `wrangler types` (task_003 §7-2). Regenerate, don't hand-edit or lint.
      "worker-configuration.d.ts",
      "workers/cron/worker-configuration.d.ts",
    ],
  },
  {
    // These use `import.meta`, top-level scripts, or wrangler's own worker
    // globals rather than the Next.js app runtime.
    files: ["workers/**/*.ts", "scripts/**/*.mjs", "scripts/**/*.ts"],
    rules: {
      "@next/next/no-html-link-for-pages": "off",
    },
  },
  {
    // Scoped to TS files so the rule lands in the same effective config as
    // eslint-config-next's own `next/typescript` block, which is what
    // registers the `@typescript-eslint` plugin.
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      // The plan bans `any` outright (project quality rule, not eslint-config-next's default).
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
];

export default config;
